### ISSUE TITLE
Documentation omits 'components-public' format for importKey

### ISSUE THREAD

**Issue by nulldozer** [rzcoder/node-rsa#103]
According to the documentation, `importKey` only supports three format strings: `'pkcs1'`, `'pkcs8'`, and `'components'`. However, importing a public key (with only n and e set in the components) requires the undocumented format string `'components-public`'. The documentation should mention the existence of this format.

**Comment by rzcoder** [comment]
You can see in docs 
> Format string composed of several parts: scheme-[key_type]-[output_type]
`components-public` === scheme: components & key_type: public
