### ISSUE TITLE
golang cross platform decrypt nodeJS encrypt

### ISSUE THREAD

**Issue by pfremm** [rzcoder/node-rsa#105]
I am attempting to encrypt some data with nodeJS, and then decrypt with golang, but I seem to be experiencing some mismatch that I cannot identify.  I've verified encrypt and decrypt worth with a key pair if I stay all in nodeJS or all in golang but not where node is encrypting and golang is doing the decrypting.  In node I am doing the following 

````
  const key = new NodeRSA(keyData, 'pkcs8-public-pem', {
    encryptionScheme: {
      scheme: 'pkcs1_oaep',
      hash: 'sha256',
      mgf: 'sha256',
    },
    signingScheme: {
      hash: 'sha1',
    },
  });
  const testString = Buffer.from('test test test');
  const cipherText = key.encrypt(testString, 'base64');
````

Then in go I am attempting to decrypt:
```
rsa.DecryptOAEP(sha256.New(),  rand.Reader, key, cipherText, nil)
```

In go I'm just going a generic error: crypto/rsa: decryption error.  Any ideas on what I am missing?

**Comment by pfremm** [comment]
As an additional test I wrote a small stub program to try encrypting from Golang to nodeJS to see if that worked.  When I use sha1 as the hash function I can encrypt in Golang and decrypt in nodeJS, but when I utilize sha256 as the hash function I get the error below:

Error: Error during decryption (probably incorrect key). Original error: Error: error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
    at NodeRSA.module.exports.NodeRSA.$$decryptKey

**Comment by pfremm** [comment]
My issue is resolved.  I didn't not realize the inherently if you run this within node, you end up using the native nodeJS crypto modules, that are not feature complete with the options specified.  It wasn't until I was actually tracing through an encrypt I could see the mgf1 function not even being called for example.  My solution ended up being:

key.setOptions({
    environment: 'browser',
    encryptionScheme: {
        'hash': 'sha256',
    }
})

As implemented this is the only way to get pkcs1_oaep working properly with go as without this the underly crypto.publicEncrypt seems to make certain assumptions.  Within openssl the native crypto module would need to expose rsa_oaep_md in addition to rsa_padding_mode and it doesn't.

**Comment by BigEgret** [comment]
Hello, I would like to ask you if I use node-rsa in the browser encryption
The browser has been successfully decrypted！ But decryption with golang failed！
Please help me, thank you very much! @pfremm 
browser：
   let dataArray = Buffer.allocUnsafe(32);
       for(let i=0;i<dataArray.byteLength;i++){
         dataArray[i] = i+32;
       }

       const NodeRSA = require('node-rsa');
       const sPubKey = new NodeRSA(setSpubKer(),'pkcs8-public');
       const sPriKey = new NodeRSA(setSpriKer(),'pkcs1-private');

      sPubKey.setOptions({
       environment: 'browser',
       encryptionScheme: {
         'hash': 'sha256',
       }
      })
      sPriKey.setOptions({
        environment: 'browser',
        encryptionScheme: {
          'hash': 'sha256',
        }
      })
     const encrypted = sPubKey.encrypt(dataArray, 'base64');
     console.log('encrypted: ', encrypted);

     const decrypted = sPriKey.decrypt(encrypted, 'buffer');
     console.log('decrypted: ', decrypted);

**Comment by pfremm** [comment]
Can you provide your golang code?

**Comment by jianjyan** [comment]
as fowllowed:

func RsaDecrypt(encryptedData []byte) ([]byte, error) {
	privInterface, err := LoadPrivateKey(RSA_PRIKEY)
	if err != nil {
		return nil, err
	}
	priv := privInterface.(*rsa.PrivateKey)
	msg := new(big.Int)
	msg.SetBytes([]byte(encryptedData))
	m := new(big.Int).Exp(msg, priv.D, priv.N)
	return m.Bytes(), nil
}


func RsaVerifySign(sig []byte, origData []byte) (error) {
	pubInterface, err := LoadPublicKey(RSA_PUBKEY)
	if err != nil {
		return err
	}
	pub := pubInterface.(*rsa.PublicKey)
	hash := sha1.New()
	if _, err := bytes.NewReader(origData).WriteTo(hash); err != nil {
		return fmt.Errorf("RsaVerifySign failed to calculate signing hash, %s", err.Error())
	}

	return rsa.VerifyPKCS1v15(pub, crypto.SHA1, hash.Sum(nil), sig)
}

**Comment by BigEgret** [comment]
@pfremm 
My colleague has decrypted the golang terminal to me.
Please help me, thank you very much!

**Comment by BigEgret** [comment]
Hello, how do I set PKCS1_OAEP to pkcs1-v1_5
你好，目前我加解密用的 PKCS1_OAEP标准，但是golang 没有基于PKCS1_OAEP的签名和验签的方法
 golang用rsa.SignPKCS1v15()签名后，用node-rsa的key.verify()对数据验签失败
而且node-rsa key.sign()对数据签名后和 golang用rsa.SignPKCS1v15() 签后  的数据比对也不一样 
请问怎么将node-rsa的PKCS1_OAEP 设置为pkcs1-v1_5 呢   @pfremm

**Comment by jastisriradheshyam** [comment]
@pfremm by setting 
`environment: 'browser'`
Decryption worked like charm, thanks

**Comment by evgenybron** [comment]
> pkcs1_oaep



> My issue is resolved. I didn't not realize the inherently if you run this within node, you end up using the native nodeJS crypto modules, that are not feature complete with the options specified. It wasn't until I was actually tracing through an encrypt I could see the mgf1 function not even being called for example. My solution ended up being:
> 
> key.setOptions({
> environment: 'browser',
> encryptionScheme: {
> 'hash': 'sha256',
> }
> })
> 
> As implemented this is the only way to get pkcs1_oaep working properly with go as without this the underly crypto.publicEncrypt seems to make certain assumptions. Within openssl the native crypto module would need to expose rsa_oaep_md in addition to rsa_padding_mode and it doesn't.



currently in the native nodejs crypto module you can use: 
crypto.privateDecrypt(
	{
		key: privateKey,
		padding: crypto.constants.RSA_PKCS1_OAEP_PADDING,
		oaepHash: "sha256",
	},
    ...
