### ISSUE TITLE
OAEP MD5 MGF1 padding

### ISSUE THREAD

**Issue by bharathimit** [rzcoder/node-rsa#106]
Hi, 

I am trying to do encryption with OAEP MD5 MGF1 padding. But the below code doesn't consider the encryptionScheme.hash value at all. It always defaults to SHA1. Could you please guide me what it is going wrong ?

var NodeRSA = require('node-rsa');
var fs = require('fs');
var publicKey = '-----BEGIN PUBLIC KEY-----\n*****\n-----END PUBLIC KEY-----';
var privateKey = '-----BEGIN RSA PRIVATE KEY-----\n*****\n-----END RSA PRIVATE KEY-----'
const constants = require('constants');
var options1 = {
  environment: 'node',
  encryptionScheme: {
    scheme: 'pkcs1_oaep',
    hash: 'md5', //hash using for scheme
  }
}
var text = 'This is the string to be encrypted using RSA!';
var encryptKey = new NodeRSA(publicKey, 'pkcs8-public', options1);
encryptKey.setOptions(options1)

var encrypted = encryptKey.encrypt(text, 'base64');
console.log(encrypted);
console.log(encryptKey.isPublic(true))

var options2  = {
  environment: 'node',
  encryptionScheme: {
    scheme: 'pkcs1_oaep', //scheme
    hash: 'sha256', //hash using for scheme
  }
}

var decryptKey = new NodeRSA(privateKey, 'pkcs1', options2);
decryptKey.setOptions(options2)
var decrypted = decryptKey.decrypt(encrypted, 'utf8');
console.log('decrypted: ', decrypted);

**Comment by rzcoder** [comment]
Node environment not support hash function option. Use `browser` environment if there any reason for change default hash function :<
