### ISSUE TITLE
encrypte with javascript ( client )

### ISSUE THREAD

**Issue by parsibox** [rzcoder/node-rsa#108]
hi
i encode in node js with this code  ( my text is too long utf8  )
```
var encrypted = key.encrypt(text, 'base64');
```
it work ok and decode is ok 
but i can not encode data in client side to send long text to my node js server
i understand  i most use RSA/NONE/OAEPWithSHA1AndMGF1Padding for encoding 
can you write an example for encoding and decoding long utf8 text in client side with publickey?
i found https://github.com/digitalbazaar/forge but this can not do  RSA/NONE/OAEPWithSHA1AndMGF1Padding 
please help me
thanks

**Comment by Eusebius1920** [comment]
Of course encrypted is always changing with each encryption. Modern encryption schemes require that the encryption **of the same information** is different each time it is encrypted (with the same key).

See CPA (and CCA) security for further information.
