### ISSUE TITLE
Encoding too long (and i'm using the private key)

### ISSUE THREAD

**Issue by PierreTrp** [rzcoder/node-rsa#109]
Error : 
![pmemm](https://user-images.githubusercontent.com/3466281/39570397-816ed692-4ec8-11e8-9aa3-e88df36dd83f.png)

My code :
```
Fs.readFile('./private.pem', 'utf8', function (err,data) {
    console.log(data);
    RSA = new NodeRSA(data, 'pkcs1');
});

```

The private key (using `openssl genrsa -des3 -out private.pem 2048`) :

![pem](https://user-images.githubusercontent.com/3466281/39570286-22b4738c-4ec8-11e8-9c09-3594d80596d1.png)

node -v : 9.10.1
I tested the private/public keys in PHP and it works well.

@rzcoder

**Comment by PierreTrp** [comment]
This included by default when you gen a basic key with openssl

`openssl genrsa -des3 -out private.pem 2048`

**Comment by bernardoadc** [comment]
Same problem here. A "simple" additional parameter would solve it: `key.importKey(keyData, [format], [passphrase]);`
