### ISSUE TITLE
throw newInvalidAsn1Error(' encoding too long')

### ISSUE THREAD

**Issue by MKC-TylerCH** [rzcoder/node-rsa#115]
var NodeRSA = require('node-rsa');

var public_key='lOZHW2ZkWmE9OmElmWFizJRnm7/lYc+5NlN9yzJOif1LRkjw8lVndWpoWuNBO4+iASd0WPXmyIKQUpgTqFv5YnaALqKhE89CBuk12bDxUzU50N09SBNHB4cjzd0ql7m9WybWcjLSglJIvY4YuD2PnAEYrMcP18xlp5zyRZfJ+Ys=';

var key = new NodeRSA();

key.importKey(public_key, 'pkcs1-public');

var decrypted = key2.decrypt(encrypted, 'utf8');
console.log('decrypted: ', decrypted);

when i run this script,but there is one error: throw newInvalidAsn1Error(' encoding too long')
P.S:i got the public_key value from other team to decrypt  formauthentication cookie,but when i tried to run the script,the error occured.
i want to know why? thanks a lot!!

**Comment by rzcoder** [comment]
pls look at readme how public key should look

**Comment by MKC-TylerCH** [comment]
sorry,i don't understand your mean, in fact i want to use public key to decrypt the cookie,not private key,but it doesn't work.please provide more detail information.thanks a lot!
