### ISSUE TITLE
Verify Sign with public key

### ISSUE THREAD

**Issue by lucaspojo** [rzcoder/node-rsa#118]
Hi, 

How to verify signature of string from other person with his public key ?

I try with 

`rsakey.verify(identityProofHash, identityProofHash_Signed , "utf-8", "hex")`

But its with my own rsakey, and I only have the public key of the author of the signature.

Thx.

**Comment by William-McGonagle** [comment]
Hey, 
Did you ever figure out how to fix this? I got the signing process to work, but when I try and verify the signed data, the verify function returns false. I know this library isn't the most well maintained, but it is the easiest to use (when it works). If you know anything to help, just tell me.

**Comment by crhistianramirez** [comment]
@William-McGonagle  you ever figure this out?

**Comment by William-McGonagle** [comment]
Hey @crhistianramirez, I was never able to figure it out- sorry!
