### ISSUE TITLE
How to get the public key in OpenSSH format?

### ISSUE THREAD

**Issue by nicroto** [rzcoder/node-rsa#119]
First off - thanks! node-rsa is great.

The issue I have, has to do with a format for the public key, which doesn't seem to be available - this is the format that I need:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtgNcWBuAtAuhXr3ThTmjmTug0WSXzkmHnLg6fiqeCtswRrKCwZlVpj0N8MyOZiBUkBupx590pruqxDNgFf755HaYyMPi+RUUwD52Aci/VKj2QAtjMJwNTigGUiFEIxXOWjbZtLl+OitH+1zjo6if+Xmgjx20TKUBBtsxd8r+z/xL86j6eDE8R3bj5nFMSi5+hE6uiclfhRyNJGnY0Z5ylBpQhWrYqzDV1ckp/IboDMOBTgexiMhUKMN5t+utmhqGp/HqAKd9wCzh3AprpfKUJ2jbb69S+yfgdtaxPgs5Zwj/nC7RlpTJEZlNfq6KyPKJFIwHm4bsgrC21+dX9Bu67 tsenkov@Nikolays-MacBook-Pro.local
```

Is there a setting I am missing? If not is there a way that you know of, that I can convert a public key generated within node-rsa, without executing (child-process->exec) any CLI tools?

Thanks.

**Comment by Cherry** [comment]
I've been playing with this myself today and it doesn't appear as if this is a feature of `node-rsa` directly. I have gotten things to work using `node-forge` though, as follows:
```javascript
const NodeRSA = require('node-rsa'),
	forge = require('node-forge');

const key = new NodeRSA();
key.generateKeyPair(2048, 65537);
const publicKey = forge.pki.publicKeyFromPem(key.exportKey('pkcs1-public-pem'));
console.log({
	private: key.exportKey('pkcs1-private-pem'),
	public: forge.ssh.publicKeyToOpenSSH(publicKey, 'user@domain.tld'),
});
```
