### ISSUE TITLE
Using PSS while keeping the default values for the rest

### ISSUE THREAD

**Issue by Berkmann18** [rzcoder/node-rsa#121]
I was looking for an RSA-PSS signature scheme library and stumbled upon this one, I've been playing around with it but it doesn't seem to allow me to actually set the signature scheme and other options like the hash (since SHA-1 is broken) and was wondering how could I do that while keeping the other parameters as default.
The reason why I'm looking into using this is that I'm planning on implementing systems where several users will have their own key pairs and signatures (so no point generating pem files like for a web server).

**Comment by Berkmann18** [comment]
@rzcoder Has this been actually resolved?

**Comment by rzcoder** [comment]
Resolved what? You can set signing hash over `signingScheme.hash` option.
