### ISSUE TITLE
  client browser running error in angular 6

### ISSUE THREAD

**Issue by jingxin2015** [rzcoder/node-rsa#128]
![22](https://user-images.githubusercontent.com/16143766/44332728-5e152700-a49f-11e8-94f3-770a70f7853b.png)

thanks.

**Comment by jingxin2015** [comment]
NodeRSA nodeRSA = new NodeRSA({b: 2048});
nodeRSA.setOptions({environment: 'browser'});
nodeRSA.encrypt(plaintext, 'utf8');
代码报上面的错误，已经设置环境为browser了，为什么还会报错呢？

**Comment by sydneyluce** [comment]
@rzcoder & @jingxin2015 Did nodeRSA.setOptions({environment: 'browser'}); solve this issue?
