### ISSUE TITLE
error: constants is not defined

### ISSUE THREAD

**Issue by InkoiWong** [rzcoder/node-rsa#133]
node: 8.12.0
npm: 6.4.1
I just import it into my project like this:
import NodeRSA from 'node-rsa';
console.log('NodeRSA', NodeRSA)
and then got some error:
module "npm/node-rsa/src/constants" is not defined 
Error: module "npm/node-rsa/src/constants" is not defined
Please give some helps thanks

**Comment by jonyeezs** [comment]
if you are using webpack, i added this to my webpack.config.js file

```js
module.exports = {
  plugins: [
    ...
  node: { constants: true, crypto: true },
   ...
};
```

seems to have worked for me.
