### ISSUE TITLE
Uint8Array byte[] Data after decryption is incorrect

### ISSUE THREAD

**Issue by BigEgret** [rzcoder/node-rsa#135]
const cNonceBuf = new ArrayBuffer(32);
      let c_Nonce = new Uint8Array(cNonceBuf);

      const NodeRSA = require('node-rsa');
      const key = new NodeRSA({b: 512});

      const encrypted = key.encrypt(c_Nonce, 'buffer');
      console.log('encrypted: ', encrypted);

      const decrypted = key.decrypt(encrypted, 'buffer');
      console.log(decrypted);

Data after decryption is incorrect?
对arrayBuffer加密，解不出来加密前的数据!是不支持这种数据类型的加密吗？
请问有办法解决吗？

**Comment by BigEgret** [comment]
@rzcoder

**Comment by BigEgret** [comment]
@rzcoder  你好，能帮我解答下这个问题吗  谢谢！

**Comment by rzcoder** [comment]
try convert c_Nonce to Buffer before encrypt

**Comment by BigEgret** [comment]
非常感谢! 按你说的确实解决了我的问题
我现在直接用Buffer了  没有使用arrayBuffer

**Comment by BigEgret** [comment]
I have a problem at the moment and want your help @rzcoder 
Encrypted with node-rsa on the browser side, but decrypt failed in golang
现在我遇到一个问题，想获得你的帮助!
在浏览器端加密但是在golang里解密失败

**Comment by BigEgret** [comment]
Hello, how do I set PKCS1_OAEP to pkcs1-v1_5
你好，目前我加解密用的 PKCS1_OAEP标准，但是golang 没有基于PKCS1_OAEP的签名和验签的方法
golang用rsa.SignPKCS1v15()签名后，用node-rsa的key.verify()对数据验签失败
而且node-rsa key.sign()对数据签名后和 golang用rsa.SignPKCS1v15() 签后 的数据比对也不一样
请问怎么将node-rsa的PKCS1_OAEP 设置为pkcs1-v1_5 呢 @pfremm

**Comment by BigEgret** [comment]
Hello, how do I set PKCS1_OAEP to pkcs1-v1_5
你好，目前我加解密用的 PKCS1_OAEP标准，但是golang 没有基于PKCS1_OAEP的签名和验签的方法
golang用rsa.SignPKCS1v15()签名后，用node-rsa的key.verify()对数据验签失败
而且node-rsa key.sign()对数据签名后和 golang用rsa.SignPKCS1v15() 签后 的数据比对也不一样
请问怎么将node-rsa的PKCS1_OAEP 设置为pkcs1-v1_5 呢 @rzcoder
