### ISSUE TITLE
打包时报错

### ISSUE THREAD

**Issue by HbuJiaTian** [rzcoder/node-rsa#137]
打包时node-rsa报错，请问应该怎么处理？
Unexpected token: name (openingBoundaryIndex) [./~/_node-rsa@1.0.2@node-rsa/src/utils.js:94,0][userCenter/js/vendor.7245850e9967999048ca.js:359,8]

![image](https://user-images.githubusercontent.com/10797390/50819324-ae185b80-1364-11e9-9396-ba696dbf1282.png)

**Comment by HbuJiaTian** [comment]
求解答

**Comment by HbuJiaTian** [comment]
@rzcoder 请问有人反馈过这个问题吗？

**Comment by HbuJiaTian** [comment]
Wrong Packing，What should I do?
![image](https://user-images.githubusercontent.com/10797390/50819434-02bbd680-1365-11e9-89dc-e8bacedafc29.png)

**Comment by rzcoder** [comment]
Be sure what you packager supports es6 syntax.

**Comment by HbuJiaTian** [comment]
Most packages are converted to Es5 by themselves. Does node-rsa not? How do I configure it here? I had no problem packing before，It started to go wrong yesterday.

![image](https://user-images.githubusercontent.com/10797390/50829428-71a62900-137f-11e9-8f26-03e3535f26b0.png)

**Comment by HbuJiaTian** [comment]
I have known the Reason, the lastest version  you have used 'es6', but the others use 'es5'

![image](https://user-images.githubusercontent.com/10797390/50830954-5be73280-1384-11e9-88bb-69ad52cee1d8.png)

**Comment by rzcoder** [comment]
In ver 1.0.0 Node < 8.11.1 support dropped (mean also es5 support).
