### ISSUE TITLE
Decryption Functionality Broken

### ISSUE THREAD

**Issue by cjfritz** [rzcoder/node-rsa#145]
I am attempting to implement simple public key cryptography with this library's RSA functions, but decryption seems to be broken.

I have two "users", Alice and Bob.  Both Alice and Bob (code in separate files) create a new empty key via `const key = new nodeRSA()`.  Then, they both generate a 2048 bit public and private key pair via the function `key.generateKeyPair(2048)`.  They both then give each other their public keys by exporting them from the key with `key.exportKey('pkcs8-public-pem')` and storing them into separate files and reading them in with fs.  Alice then attempts to write a message to bob by passing both the string message and bob's public key into the function below

```
module.exports.writeMessage = (message, key) => {
    const k = new rsa(key, 'pkcs8-public-pem')
    const cipherText = k.encrypt(message, 'hex');
    console.log('Saving "${cipherText}" to ctext.txt');
    fs.writeFileSync('ctext.txt', cipherText);
};
```

Then, when bob goes to read the message, he passes in his full key and decodes the message from ctext.txt as shown in the function below

```
module.exports.readMessage = key => {
    const encryptedMessage = fs.readFileSync('ctext.txt');
    const message = key.decrypt(encryptedMessage, 'utf8');
    return message;
};
```

Encryption works just fine, and Alice is able to send the ciphertext to ctext.  The problem comes when bob calls the readMessage function and attempts to decipher the text.  Both the Alice and Bob programs were activated and their keys remained unchanged throughout this process.  The below error occurs on deciphering:
```
Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key
    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/Users/jisacf1/College/SeniorYear/Spring2019/CompSec/HW3/node_modules/node-rsa/src/NodeRSA.js:301:19)
    at NodeRSA.module.exports.NodeRSA.decrypt (/Users/jisacf1/College/SeniorYear/Spring2019/CompSec/HW3/node_modules/node-rsa/src/NodeRSA.js:249:21)
    at Object.module.exports.readMessage.key [as readMessage] (/Users/jisacf1/College/SeniorYear/Spring2019/CompSec/HW3/Part2/rsaReadWrite.js:7:25)
    at inquirer.prompt.then (/Users/jisacf1/College/SeniorYear/Spring2019/CompSec/HW3/Part2/bob.js:42:43)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I've tried changing padding schemes to no avail as well.  Any help would be appreciated greatly.

**Comment by rzcoder** [comment]
Can you provide minimal repo for reproduce?

**Comment by cjfritz** [comment]
I figured out what the issue was.  I apologize, the issue did not have to do with decryption itself.  The filesystem was encoding my cipher text incorrectly by default, so when I went to read the cipher text from the file after it was written, it was read back in a corrupted format.  Changing the default file encoding from utf8 to hex fixed the issue.
