### ISSUE TITLE
ie10 不兼容

### ISSUE THREAD

**Issue by tttonight** [rzcoder/node-rsa#148]
代码里面包含const和let，ie10以下兼容不了： src/formats/pkcs1.js 和 src/formats/pkcs8.js ,需要都改为var
![image](https://user-images.githubusercontent.com/20434301/53935369-fcd23f80-40e0-11e9-9ce3-a7c28a12ba8e.png)

![image](https://user-images.githubusercontent.com/20434301/53935381-08be0180-40e1-11e9-9e0e-59027e3e15a7.png)

**Comment by YAN7** [comment]
this can be solved by webpack config: 
```
{
                test: /\.js$/,
                include: /node_modules\/node-rsa/,
                loader: 'babel-loader',
                options: {
                    presets: ["@babel/preset-env"],
                },
            },
```
