### ISSUE TITLE
Can't decrypt with public key 

### ISSUE THREAD

**Issue by OmarFarrag** [rzcoder/node-rsa#150]
```
const key = new NodeRSA(privateKey);
// tried with and without the following command
// key.setOptions({encryptionScheme:'pkcs1'});  
key.encrypt(certificate,'base64');

/////////////////////////////////////////////////////////
var k2 = new NodeRSA(publicKey,'pkcs8-public');
var k = k2.exportKey('pkcs1-public');
var kk = new NodeRSA(k,'pkcs1-public');
kk.setOptions({encryptionScheme:'pkcs1'});
kk.decryptPublic(certificate,'utf8');
```

gets the error:
node_modules\node-rsa\src\NodeRSA.js:301
            throw Error('Error during decryption (probably incorrect key). Original error: ' + e);
            ^

Error: Error during decryption (probably incorrect key). Original error: Error: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01
    at NodeRSA.module.exports.NodeRSA.$$decryptKey ("directory path"\node_modules\node-rsa\src\NodeRSA.js:301:19)
    at NodeRSA.module.exports.NodeRSA.decryptPublic "file path"\node-rsa\src\NodeRSA.js:267:21)
    at "function" "directory path"\main.js:54:24)
    at "directory path"\main.js:67:9
    at IncomingMessage.<anonymous> (directory\main.js:31:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by OmarFarrag** [comment]
I got it.Encryption should be done with encryptPrivateKey and then needless to set the encryption scheme.. like this :
```
const key = new NodeRSA(privateKey);
key.encryptPrivate(certificate,'base64');

//////////////////////////////////////////

var k2 = new NodeRSA(publicKey,'pkcs8-public');
var k = k2.exportKey('pkcs1-public');
var kk = new NodeRSA(k,'pkcs1-public');
kk.decryptPublic(certificate,'utf8');
```

**Comment by cristicmf** [comment]
I use the java can decrypt message. while, the node-sra can not made it .
