### ISSUE TITLE
randomBytes is not a function

### ISSUE THREAD

**Issue by glennflanagan** [rzcoder/node-rsa#156]
I'm not 100% sure if this is a `node`, `webpack`, `crypto-browserify` or `node-rsa` issue, but I have a single page web app which is using the `node-rsa` package and when my app is in production and I try to run `.encrypt(...` I get the error `o.randomBytes is not a function`. 

Turning off all minification I get `crypt.randomBytes is not a function` so it seems it's not a problem caused by minification.

But I have an identical wepback config for development which uses webpack-dev-server and when I run `.encrypt(...` it works fine. This only happens when webpack outputs the files to disk.  

This is my setup
```js
import NodeRSA from 'node-rsa';

const encryptionKey = new NodeRSA(publicKey, 'pkcs8-public', {
  environment: 'browser',
  encryptionScheme: 'pkcs1',
  signingScheme: 'sha256',
});

// Password removed from example for obvious reasons
const secret = encryptionKey.encrypt(password, 'base64');

```

I have added a breakpoint where the `o.randomBytes is not a function` error occurs and I can see that `o` (or `crypt` unminified) is defined and seems to have all the methods that the Node built-in has, but for some reason `randomBytes` is undefined.

Has anyone else had this issue with running it in a browser?

**Comment by jstevenson** [comment]
Did you find a solution to fix this, or did you go a different path?

**Comment by glennflanagan** [comment]
@jstevenson this was so long ago I can’t even remember what project this was for 😬 sorry.
