### ISSUE TITLE
Why it is always "buffer not defined" in the console?

### ISSUE THREAD

**Issue by CC2013** [rzcoder/node-rsa#158]
[Here](https://stackblitz.com/edit/rxjs-awxk9k?devtoolsheight=60) is my example. And I installed "buffer" already, but still has the problem, I have no idea about it. Can anyone help? Really appreciate it!

**Comment by learntheropes** [comment]
You can use [this](https://www.npmjs.com/package/@learntheropes/node-rsa) fork.
