### ISSUE TITLE
Running in a browser, decryption is slow

### ISSUE THREAD

**Issue by ryanlid** [rzcoder/node-rsa#161]
Running in a browser, when there is more content, decryption is slow and takes a long time

在浏览器中运行时，内容比较多的时候，解密需要很长时间，解密速度比 [lsqswl/rsaencrypt](https://github.com/lsqswl/rsaencrypt)  或者[travist/jsencrypt](https://github.com/travist/jsencrypt) 慢很多

不过使用它们，加密内容较多的时候会出错 lsqswl/rsaencrypt#2

**Comment by ryanlid** [comment]
This is my online code

https://codesandbox.io/s/github/ryanlid/js-rsa-demo

**Comment by obie3** [comment]
It is even slower on mobile devices trying to decrypt less content, any way to help increase speed of decryption as the lag is so obvious thanks in adavance

**Comment by Fengjing95** [comment]
同一份公私钥， 我用 jsencrypt 加密再用 node-rsa 解密为啥会失败啊   T.T
