### ISSUE TITLE
InvalidAsn1Error: Expected 0x6: got 0xa0

### ISSUE THREAD

**Issue by antoniuslin** [rzcoder/node-rsa#163]
Hello,

When I generate the pairs using this module, everything seems to work as expected.

However, in my one of tasks, I need to use a public certificate provided to me by another party (X509) in order to verify a SAMLResponse signature. How do I import an X509 cert using this module?

I tried the following approach with various "pub" format designation, but none seems to work.

```js
let publicKey = `-----BEGIN PUBLIC KEY-----\n${samlResponsePubCert}\n-----END PUBLIC KEY-----`;

const NodeRSA = require('node-rsa');
let rsaKey = new NodeRSA();
rsaKey.importKey(publicKey, 'pkcs8-public');
// tried 'component-public' and just 'public' resulting in other (similar) errors
```

and it resulted in `InvalidAsn1Error` snippet below:

```js
node_modules/asn1/lib/ber/reader.js:169
    throw newInvalidAsn1Error('Expected 0x' + tag.toString(16) +
    ^

InvalidAsn1Error: Expected 0x6: got 0xa0
```

What step did I miss?

Thanks much.

**Comment by rzcoder** [comment]
This format not supported currently.
