### ISSUE TITLE
exportKey returning key in PKCS#8 format that encodes negative numbers

### ISSUE THREAD

**Issue by wartab** [rzcoder/node-rsa#169]
I was trying to encode a private RSA key based on their components using the PKCS#8 format, but the resulting encoded key did end up not being valid and was unusable when decrypting data (apparently Electron's node uses BoringSSL instead of OpenSSL, which seems to be stricter on invalid input).

I got a lot of help from a member of Electron, who figured out that my issue came from node-rsa's resulting formatted key encoding negative numbers, which is invalid.

He pointed me to this:
https://github.com/openssl/openssl/blob/master/crypto/asn1/x_bignum.c#L16-L19

You can read more about the discussion and initial issue I had here:
https://github.com/electron/electron/issues/21876

**Comment by rzcoder** [comment]
If you use node environment I recommend switch to native node crypto (https://nodejs.org/dist/latest-v12.x/docs/api/crypto.html) module. Now it have all necessary functions like `generateKeyPair` and others.
