### ISSUE TITLE
import public key .cer error

### ISSUE THREAD

**Issue by sabbin** [rzcoder/node-rsa#170]
Hello,

I have a public key with the extension .cer that I am trying to import.

```js
const key  = new NodeRSA(public_key, 'pkcs8-public')
```
But I keep getting `InvalidAsn1Error: encoding too long`

If I put the type `'pkcs8-public-der` I get `Error: Unsupported key format`

The certificate has the following structure and props

```
Public Key Algorithm: rsaEncryption
Public-Key: (1024 bit)
Signature Algorithm: md5WithRSAEncryption
```
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
Am I doing something wrong or the certificate is not supported?

**Comment by rzcoder** [comment]
This format is not supported.
