### ISSUE TITLE
Support for pkcs1 v1.5

### ISSUE THREAD

**Issue by ezquire** [rzcoder/node-rsa#171]
I have an API endpoint that requires v1.5 padding will this be supported in future versions?

**Comment by hexcola** [comment]
Hi, @ezquire , I met the same issue, and check https://github.com/rzcoder/node-rsa#options out. 
Since `pkcs 1 v1.5` has some flaws, rsa-node use `pkcs1_oaep` as default, if you still want to use it, you can change the `encryptionScheme` like this:

```js
key.setOptions({ encryptionScheme:  'pkcs1'})
```
