### ISSUE TITLE
typescript constructor for components is incorrect

### ISSUE THREAD

**Issue by dougmacdoug** [rzcoder/node-rsa#172]
The following code does not work:
```
const key = new NodeRSA({ n, e}, 'components-public-der'); 
```
The definition for the Typescript constructor takes a `NodeRSA.Key` which includes `KeyComponentsPublic`; however in the javascript code for NodeRSA, it actually checks if there is an object passed in and then uses `generateKeyPair` which is not the correct behavior. importKey works correctly.

A workaround:
```
const key = new NodeRSA({ n, e}, 'components-public-der'); 
key.importKey({ n, e}, 'components-public-der'); 
```
Instead of checking the key input type in javascript, you could use the schema and then fallback to generate if none is provided. I could have just passed null in javascript to avoid the generateKey call and then call import, however in Typescript you can't pass null because it doesn't match the `NodeRSA.Key` type

**Comment by rzcoder** [comment]
You should ask maintainer of https://www.npmjs.com/package/@types/node-rsa
