### ISSUE TITLE
Not working for React Native in iOS. Works for Android

### ISSUE THREAD

**Issue by AnoopN01** [rzcoder/node-rsa#174]
Getting error Unable to resolve module ‘constants ‘ from node_modules/node-rsa/src/NodeRsa.js’ 
I had to manually provide the dependencies like react-native-crypto, react-native-randombytes but the linker is failing to link the dependencies Getting error TypeError:null is not an object(evaluating ‘RNRandomBytes.seed’). This an an awesome library and the best solution for RSA with PKCS8. I would appreciate if you could support React Native iOS

**Comment by esteban199** [comment]
the same here

**Comment by rzcoder** [comment]
You need to provide some node.js modules like 'constants' while bundling.

**Comment by singolawu** [comment]
is there any fix?

**Comment by salmanm** [comment]
You can configure babel to resolve missing modules

```
npm i crypto-browserify stream-browserify constants-browserify assert-browserify
npm i babel-plugin-module-resolver -D
```

and add the following config to babel.config.js

```js
[
  'module-resolver',
  {
    ...
    alias: {
      crypto: 'crypto-browserify',
      stream: 'stream-browserify',
      constants: 'constants-browserify',
      assert: 'assert-browserify',
    },
  },
],
```

**Comment by obie3** [comment]
> 

Hi Salmanm, I tried your example, it didnt work for me, could you please paste your entire babel.config.js file. thanks

**Comment by obie3** [comment]
> You can configure babel to resolve missing modules
> 
> ```
> npm i crypto-browserify stream-browserify constants-browserify assert-browserify
> npm i babel-plugin-module-resolver -D
> ```
> 
> and add the following config to babel.config.js
> 
> ```js
> [
>   'module-resolver',
>   {
>     ...
>     alias: {
>       crypto: 'crypto-browserify',
>       stream: 'stream-browserify',
>       constants: 'constants-browserify',
>       assert: 'assert-browserify',
>     },
>   },
> ],
> ```

Hi Salmanm, I did follow your solution and it worked like charm but I got stuck with undefined variable Buffer error, I have installed it independently like I did for others that worked but the Buffer error is proving to be stubborn please any idea on what to do next. 

Thanks in anticipation

**Comment by obie3** [comment]
> > You can configure babel to resolve missing modules
> > ```
> > npm i crypto-browserify stream-browserify constants-browserify assert-browserify
> > npm i babel-plugin-module-resolver -D
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and add the following config to babel.config.js
> > ```js
> > [
> >   'module-resolver',
> >   {
> >     ...
> >     alias: {
> >       crypto: 'crypto-browserify',
> >       stream: 'stream-browserify',
> >       constants: 'constants-browserify',
> >       assert: 'assert-browserify',
> >     },
> >   },
> > ],
> > ```
> 
> Hi Salmanm, I did follow your solution and it worked like charm but I got stuck with undefined variable Buffer error, I have installed it independently like I did for others that worked but the Buffer error is proving to be stubborn please any idea on what to do next.
> 
> Thanks in anticipation

Thanks @salmanm for the help, it worked 
<img width="1060" alt="Screen Shot 2022-03-24 at 1 32 32 PM" src="https://user-images.githubusercontent.com/18898840/159917049-72736fa8-28ec-43c5-94f5-16c75803b698.png">

This is for anyone experiencing thesame in the future
