### ISSUE TITLE
RSA Unsupported key type?

### ISSUE THREAD

**Issue by DevinKott** [rzcoder/node-rsa#203]
From [here](https://github.com/rzcoder/node-rsa#110), it says that the package supports OpenSSH key types.

Yet, running something like this to generate keys:
```
ssh-keygen -t rsa -b 4096 -a 100 -f ~/test_keys/id_rsa -q -N 'some_password'
```
and loading those keys using:
```
const opensshPrivateKey = fs.readFileSync('~/test_keys/id_rsa').toString();
const opensshPriv = new NodeRSA(opensshPrivateKey);
console.log(opensshPriv);
```

Does not work. What am I doing wrong?

EDIT: It's throwing [here](https://github.com/rzcoder/node-rsa/blob/master/src/formats/openssh.js#L132).

**Comment by rzcoder** [comment]
password-encrypted keys are not supported
