### ISSUE TITLE
Can't import keys: "encoding too long"

### ISSUE THREAD

**Issue by stuartlangridge** [rzcoder/node-rsa#23]
Doing what I think is the simplest test of importing a key:

```
var rsa = require('node-rsa'); 
var key = new rsa({bits:2048});
var keydata = key.exportKey('pkcs8-public') + '\n' + key.exportKey('pkcs8'); 
var k2 = new rsa(keydata,'pkcs8');
```

throws an error:

```
InvalidAsn1Error: encoding too long
```

Am I doing something obviously wrong?

**Comment by Hexxonite** [comment]
When I try to use "Web Crypto" to generate a RSA keyset, then export the public key to pksc8 and try to encrypt a message with node-rsa I get this error.

I know this might be an unusual usecase but I'd appreciate some help at this point.
I've had so much firetrucking' trouble with different crypto libs & standards & formats & hashalgorithms & paddings and whatnot if this doesnt work out Ive spent like 10 hours researching and testing for nothing....

Example Code:

Generate (Browser):
`    crypto.subtle.generateKey(
    {
        name: "RSA-OAEP",
        modulusLength: 4096,
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
        hash: "sha-256"
    },
    true,
    ["encrypt", "decrypt"]).then(...`

Export (Browser):
`    crypto.subtle.exportKey("pkcs8", key).then((exported) => {
    const exportedAsString = ab2str(exported);
    const exportedAsBase64 = window.btoa(exportedAsString);
    resolve("-----BEGIN PUBLIC KEY-----\n"+exportedAsBase64+"\n-----END PUBLIC KEY-----");
 });`

Encrypt (Node):
`let key = new NodeRSA().importKey(publicKey, 'pkcs8-public-pem');
return key.encrypt(toEncrypt, 'base64');`

Error message:
`node_modules\asn1\lib\ber\reader.js:103
      throw newInvalidAsn1Error('encoding too long');
      ^

InvalidAsn1Error: encoding too long
    at newInvalidAsn1Error (node_modules\asn1\lib\ber\errors.js:7:13)
    at Reader.readLength (node_modules\asn1\lib\ber\reader.js:103:13)
    at Reader.readSequence (node_modules\asn1\lib\ber\reader.js:136:16)
    at Object.publicImport (node_modules\node-rsa\src\formats\pkcs8.js:153:16)
    at Object.detectAndImport (node_modules\node-rsa\src\formats\formats.js:65:48)
    at NodeRSA.module.exports.NodeRSA.importKey (node_modules\node-rsa\src\NodeRSA.js:183:22)`

**Comment by chaitanyabd** [comment]
I found this line helped (after using rsa.importKey to import the public key)
client_key.setOptions({ encryptionScheme: 'pkcs1' });
