### ISSUE TITLE
how can i use a publickey to decrypt?

### ISSUE THREAD

**Issue by shadow0162** [rzcoder/node-rsa#28]
In order to decrypt by publishkey ,I used to 'openssl_public_decrypt' in php,But in node-rsa,which method should i used?i try import the publish key ,pass verify and then decrypt the source got error.
code:
```javascript
key = new NodeRSA();
key.importKey(publicKey, 'pkcs8-public');
result = key.verify(source, signBuff);
if (result) {
	var notifydataBuf = new Buffer(notifydata, 'base64')
	var decrypted = key.decrypt(notifydataBuf, 'utf8');
	console.log('decrypted: ', decrypted);
}
```
And  error is:

> E:\RSA\node_modules\node-rsa\src\NodeRSA.js:263
>            throw Error('ErrorOriginal error: ' + e);
>                  ^
>Error: ErrorOriginal error: TypeError: Cannot call method 'abs' of null
>    at Error (<anonymous>)
>    at NodeRSA.module.exports.NodeRSA.decrypt (E:\RSA\node_modules\node->rsa\src\NodeRSA.js:263:19)
>   at Object.<anonymous> (E:\RSA\RSA.js:195:24)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>    at startup (node.js:119:16)
>    at node.js:906:3

**Comment by shadow0162** [comment]
update，
i try to use ursa(https://github.com/NodePrime/ursa).it's work.
follow code:
```javascript
var crt = ursa.createPublicKey(publicKey);
var msg = crt.publicDecrypt(notifydata, 'base64', 'utf8');
```

**Comment by rzcoder** [comment]
There's no public key decrypt, public key might be used only for encryption. Otherwise it not secure at all.
