### ISSUE TITLE
Encrypt same string using same key always returns different values

### ISSUE THREAD

**Issue by andreafdaf** [rzcoder/node-rsa#29]
I really don't know what's going on but running the following code gives the odd behavior written in the title:

```javascript
var someString = 'hello'
var key = new NodeRSA(publicKey,'pkcs8-public-pem')
console.log(key.exportKey('pkcs8-public-pem')) //returns correct key, ok
console.log(key.isPublic()) //returns true, ok
console.log(key.encrypt(someString, 'base64') === key.encrypt(someString, 'base64')) //returns false, NOT OK
```

That's really really odd!

node version 0.10.25
node-rsa version 0.2.13

**Comment by rzcoder** [comment]
It's ok, encrypted result must be different every time even for same original data (lib adds some random bytes for every encryption).
