### ISSUE TITLE
OpenSSL <--> node-rsa

### ISSUE THREAD

**Issue by transaction** [rzcoder/node-rsa#36]
Hi, I'm trying to implement encryption on iOS and decryption on node. When I read both keys in node, everything works, both with standard padding as with pkcs1, but neither of them decrypts OpenSSL encrypted base64 strings.

The OpenSLL function used is `RSA_public_encrypt(chunk_length, plain_chunk, result_chunk, rsa_publicKey, RSA_PKCS1_PADDING)`and it outputs a valid base64 string. When trying to decipher it on node-rsa I get:

`Error during decryption (probably incorrect key). Original error: Error: Key decrypt method returns null.` OpenSLL uses the pem output, the same one I use when testing in node.

Any suggestions?

**Comment by rzcoder** [comment]
Try use RSA_PKCS1_OAEP_PADDING in OpenSLL.

2015-03-18 16:17 GMT+05:00 transaction <notifications@github.com>:
> Hi, I'm trying to implement encryption on iOS and decryption on node. When I
> read both keys in node, everything works, both with standard padding as with
> pkcs1, but neither of them decrypts OpenSSL encrypted base64 strings.
>
> The OpenSLL function used is RSA_public_encrypt(chunk_length, plain_chunk,
> result_chunk, rsa_publicKey, RSA_PKCS1_PADDING)and it outputs a valid base64
> string. When trying to decipher it on node-rsa I get:
>
> Error during decryption (probably incorrect key). Original error: Error: Key
> decrypt method returns null. OpenSLL uses the pem output, the same one I use
> when testing in node.
>
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Best regards,
Sergey Vychegzhanin.

Email: rzcoder@gmail.com
Skype: rzcoder

**Comment by transaction** [comment]
I made a mistake in the code, no issues with OpenSSL anymore

**Comment by Frange** [comment]
I was having a similar issue with Android and "RSA_PKCS1_OAEP_PADDING"  does the trick. Thanks rzcoder !!!
