### ISSUE TITLE
Use third party BitInteger library

### ISSUE THREAD

**Issue by benhutchins** [rzcoder/node-rsa#37]
You should get rid of jsbn and use https://github.com/peterolson/BigInteger.js, which fixes a few bugs that exists with the jsbn that was written many years ago.

**Comment by zarmack** [comment]
Tom Wu's [JSBN](http://www-cs-students.stanford.edu/~tjw/jsbn/) implement [Barrett's Reduction](https://en.wikipedia.org/wiki/Barrett_reduction) and [Montgomety Modular Multiplication](https://en.wikipedia.org/wiki/Montgomery_modular_multiplication) on ````ModPow()```` method. This makes the ````ModPow()```` is almost ten times faster on JSBN.
