### ISSUE TITLE
Generates the same key every time

### ISSUE THREAD

**Issue by bnolan** [rzcoder/node-rsa#38]
I may be doing something wrong, but under node 0.12:

```
var generator = new NodeRSA({b: 256});

for (var x = 0; x < 5; x++) {
  key = generator.generateKeyPair();
  console.log(fingerprint(key.exportKey('public'), 'sha1'));
```

output:

```
06:f1:22:df:66:55:31:63:96:e4:94:89:86:e8:97:23:82:82:2a:16
06:f1:22:df:66:55:31:63:96:e4:94:89:86:e8:97:23:82:82:2a:16
06:f1:22:df:66:55:31:63:96:e4:94:89:86:e8:97:23:82:82:2a:16
06:f1:22:df:66:55:31:63:96:e4:94:89:86:e8:97:23:82:82:2a:16
06:f1:22:df:66:55:31:63:96:e4:94:89:86:e8:97:23:82:82:2a:16
````

**Comment by rzcoder** [comment]
Not repeated for me.
First of all, you use `generateKeyPair(bits, exp)` wrong:
`var generator = new NodeRSA({b: 256});` there you already generated 256 bit key, and then you call `generator.generateKeyPair()` it generated new key with default parameters (2048 bits length).

Check this, make new key every time for me.
```
var NodeRSA  = require('node-rsa');
var generator = new NodeRSA();
for (var x = 0; x < 5; x++) {
  key = generator.generateKeyPair(256);
  console.log(key.exportKey('public'));
}
```

**Comment by bnolan** [comment]
Sorry, the fingerprint function I was using was incorrect. My mistake. Thank you for a great package. :)
