### ISSUE TITLE
How to use the keys in c#

### ISSUE THREAD

**Issue by krini** [rzcoder/node-rsa#39]
Do you have an example on how to import the public key generated by node-rsa in c# and encrypt a message?

In c# we keep getting the message that the key is incorrect, however it works perfekt in nodejs.
We try to create a pcks1-oaep key.

**Comment by rzcoder** [comment]
http://stackoverflow.com/questions/243646/how-to-read-a-pem-rsa-private-key-from-net

**Comment by krini** [comment]
That is actually the example we try to use. However its only the public key we export.
Which version of pkcs1 are you using?
