### ISSUE TITLE
Create public key from component of modulus and exponent

### ISSUE THREAD

**Issue by xavieryao** [rzcoder/node-rsa#43]
How can I generate a public key using given modulus and exponent?

**Comment by rzcoder** [comment]
You can do it like this

```
var modulus = new Buffer('8a96279f5da3cfe816bc6bfc97eef08f366f364a021a59d326516b7deb68e3bbe9a832f7512a4ef3178c432729330f09c479c058000709e1938b1c89786db78f', 'hex');
var exp = new Buffer(4);
exp.writeInt32BE(65537, 0);

key = new NodeRSA();
key.keyPair.setPublic(modulus, exp);

var text = 'Hello RSA!';
var encrypted = key.encrypt(text, 'base64');
console.log('encrypted: ', encrypted);
```

But generally this API is not public and can be removed in future versions.

**Comment by xavieryao** [comment]
Thank you so much for your sincere help!

发自我的 iPhone

**Comment by naugtur** [comment]
Could a version of this API be exposed?

**Comment by naugtur** [comment]
Actually, it doesn't have to.
https://github.com/tracker1/node-rsa-pem-from-mod-exp can be used to convert from mod+exp to an acceptable format

(and then node-rsa splits it back I suppose, but it's not a lot of work compared to the actual crypto operations)

**Comment by rzcoder** [comment]
Hey,
I just added new api for import/export key use raw components, try it.

**Comment by PhilipGarnero** [comment]
I tried to use your new api to import a key with only the modulus and exponent but it did not work.
The old way is working however.

**Comment by rzcoder** [comment]
Did you set format as 'component-public'?

**Comment by PhilipGarnero** [comment]
It should be specified in the doc.
