### ISSUE TITLE
window undefined in web worker

### ISSUE THREAD

**Issue by Teelevision** [rzcoder/node-rsa#48]
When using this library in a web worker, the `window` is undefined, resulting in an error.
I updated the `detectEnvironment` method in utils.js to do
`if (typeof(window) !== 'undefined' && window)`
instead of
`if (window)`
and it fixes the error, but I'm not sure if this results in any wrong behavior.
I will comment on this issue if I find out more.

See also this explaination by MDN:
> A worker is an object created using a constructor (e.g. Worker()) that runs a named JavaScript file — this file contains the code that will run in the worker thread; workers run in another global context that is different from the current window. Thus, using the window shortcut to get the current global scope (instead of self) within a Worker will return an error.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by rzcoder** [comment]
Thanks for reporting. Fixed.
