### ISSUE TITLE
Encrypting from components incorrect

### ISSUE THREAD

**Issue by ultimate-tester** [rzcoder/node-rsa#49]
Unfortunately I am not getting correct results when encrypting based on a given exponent and modulus. The following code is not working and the second snippet is working correctly:

NOT WORKING:
```
var key = new NodeRSA({
	n: new Buffer(body['publickey_mod'], 'hex'),
	e: body['publickey_exp']
}, 'components', {encryptionScheme: 'pkcs1'});

var encryptedPassword = key.encrypt(password, 'base64', 'utf8');
```

WORKING:
```
const NodeRSA = require('node-rsa');
const getPem = require('rsa-pem-from-mod-exp');

var modulus = Buffer(body['publickey_mod'], 'hex').toString('base64');
var exponent = Buffer(body['publickey_exp'], 'hex').toString('base64');
var pem = getPem(modulus, exponent);
var key = new NodeRSA(pem, 'pkcs1-public-pem', {encryptionScheme: 'pkcs1'});
var encryptedPassword = key.encrypt(password, 'base64', 'utf8');
```

body['publickey_mod'] and body['publickey_exp'] are both HEX.

Could you please tell me why it is not producing correct results? Did I forget something?

**Comment by rzcoder** [comment]
Is `body['publickey_exp']` number (not string with digits)? Try cast it manually `e: parseInt(body['publickey_exp'], 10)`

**Comment by ultimate-tester** [comment]
That's not it unfortunately. It so happens that body['publickey_exp'] is the default and even when giving the default hardcoded it's not working.

**Comment by rzcoder** [comment]
Oh, wait, theres no way to import key from components in constructor for some reasons. Use `key.importKey()`.
