### ISSUE TITLE
Is it ok to use Math.random in cryptography?

### ISSUE THREAD

**Issue by fresheneesz** [rzcoder/node-rsa#51]
I see Math.random used in `src/libs/jsbn.js`. Is that a use that doesn't compromise security?

**Comment by rzcoder** [comment]
Did you understand what `Math.random` do?

**Comment by fresheneesz** [comment]
Nope, that's why i'm asking. I have no idea what the Miller Rabin algorithm is.

**Comment by rzcoder** [comment]
Never mind then.

**Comment by fresheneesz** [comment]
@rzcoder I assume by your abrupt closure that its fine. Would you mind explaining a bit what it is and why its fine? Someone evaluating security modules should be cautious, so that's what I'm being.

**Comment by rzcoder** [comment]
There even author comment in code, what else explain you want? You can read https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test at least and figure out what this code should do, before make issue.

**Comment by fresheneesz** [comment]
There really aren't a lot of comments in [the code](https://github.com/rzcoder/node-rsa/blob/master/src/libs/jsbn.js) and I did already wikipedia the algorithm - its a bit over my head I'm afraid. Well I guess I'll defer to authority in this case.
