### ISSUE TITLE
Cleanly separate node and browser versions

### ISSUE THREAD

**Issue by fresheneesz** [rzcoder/node-rsa#52]
Currently, I'm getting an error when bundling via webpack because its trying to bundle io.js . Instead of having a 'brower' `environment` flag, I propose having a completely separate file that doesn't have any nested reference to file not required by the browser. That way not only will errors like this not happen, but browser bundles using node-rsa will be smaller.

Would you accept a pull request for this?

**Comment by rzcoder** [comment]
Separated file to config one lib in project, i understood you right? Bad idea if so.
Any way, i guess you should just add json-loader to your webpack config to fix the problem :wink:

**Comment by fresheneesz** [comment]
I'm not sure you did understand me correctly, but I'm not sure I understand you either. What i mean is have a central file called like `core-rsa.js` which exposes a method to create the module for you. That method would expect being passed the relevant module from `encryptEngines`. So then for example you could have two files: `browser-rsa.js` which would be used for browser projects, and `node-rsa.js` which would be used for node projects. For example, this is what might be inside `browser-rsa.js`:

```js
var core = require("core-rsa.js")
var js = require("./encryptEngines/js.js")

module.exports = core.createModule(js)
```

**Comment by rzcoder** [comment]
Yes, it bad idea. Also you trying solve problem that doesn't really exist.

**Comment by fresheneesz** [comment]
@rzcoder This is a problem i'm currently experiencing. It exists. The thing I'm talking about is standard practice. What about it is a bad idea? I really don't understand.

**Comment by rzcoder** [comment]
I have no problems with the assembly in webpack, if you have then your webpack not properly configured. In any case, I will not divide entry point of lib.

**Comment by fresheneesz** [comment]
@rzcoder I would really like to know why you think my suggestion is a bad idea. Maybe I'm doing everything in my life wrong?

**Comment by rzcoder** [comment]
I don't want to have 2 entry point in lib to solve **your** webpack config problem. And I don't want teach you how to code. So, end and at this point.

**Comment by fresheneesz** [comment]
@rzcoder I really appreciate your great work in making this library. But I'm disappointed that you seem to be rather hard headed about this. I DID in fact solve my webpack problem by making it ignore `io.js` and `node12.js`, but I shouldn't have to do that to use your module. It makes 0 sense to me why you "don't want to have 2 entry points" - its the obvious solution and has no downsides. 

My problem is solved for me, I was hoping that you'd cooperate with me to improve this module for others - ie people who aren't you and me.

**Comment by GianniCarlo** [comment]
@fresheneesz  hey fresheneesz, how did you solve it with webpack? in my webpack config, I ignored with `noParse` both files `io.js` and `node12.js` but when I use the bundle I got some errors. Can you share your webpack config? just to discard the possibility that my configuration is wrong. Thanks

**Comment by fresheneesz** [comment]
@GianniCarlo I used `new webpack.IgnorePlugin(/(io\.js|node12\.js)$/, /node-rsa/)`. See the details here: https://github.com/webkey-auth/webkey-auth.github.io/blob/master/buildUtil.js

**Comment by GianniCarlo** [comment]
thanks @fresheneesz ! looks like my problem lies somewhere else on `Buffer` being undefined when including `node-rsa` with webpack

**Comment by fresheneesz** [comment]
np
