### ISSUE TITLE
Environment detection

### ISSUE THREAD

**Issue by Eusebius1920** [rzcoder/node-rsa#53]
While fixing the detection for webpack commit fb40aed60cbe540decd2bb9be3b5688708b82eb0 breaks the node-detection for nwjs or electron platform, which is a Chromium bundled with nodejs. There node-rsa runs in 'browser' although there is a fully featured node environment... Prior to this commit the environment was correctly identified as 'node'.

From my understanding using the node-implementation is preferred over the pure javascript (eg due to perfomance)

**Comment by rzcoder** [comment]
It would be good to remove environment detection and make feature detection instead, but dunno when I'll have time to it (PR welcome). 
btw you can manually set environment to `'node'`.
