### ISSUE TITLE
importKey Asn1Error: Expected 0x30: got 0x2

### ISSUE THREAD

**Issue by julianpr** [rzcoder/node-rsa#60]
I'm trying to import a public key:

```
var key = new NodeRSA();

var testKey = '-----BEGIN PUBLIC KEY-----
MIIBCgKCAQEAmMa/uxBgK32tNSBeHUEDjqeLqPV3Ertu/clp6Pu11Om4KdBaMa5l
p9IVK6MbcttPxWHmxCoizS5yUQaHgrSDNSKLpLJA9sW/3toVYjqMjGNlFuYnpwN+
LeKVSqxJXd4Qfqp3Xr6tQewviejAH854sSBhnEv3xOk33xvVgvR4Nbfn6c9g2WzG
RLjE4l2YyMJaim7RACLapV9+aF+HBrIp8TU/yEEuycYFvHDEX8Edv0oJzsZQzF1K
wexxgHFEiA20uITR4O4m2FNHDDsEDATfT6wboq6Kiyt9lVhadVRAC4F4Ib8rXlFv
zcbo5Zq3Ls479VrdosjJ90R2FiYRYv1wSwIDAQAB
-----END PUBLIC KEY-----';

key.importKey(testKey, 'pkcs8-public');
```

and I'm getting this on importKey:
`InvalidAsn1Error: Expected 0x30: got 0x2`

Is there something I'm doing wrong?

**Comment by rzcoder** [comment]
```BEGIN RSA PUBLIC KEY```

```pkcs1-public```

**Comment by julianpr** [comment]
Thank you, it seems to work now. Just for clarification, why wasn't it working with pkcs8 format?

**Comment by JoakimCh** [comment]
This issue is NOT resolved!
pkcs8 keys can not be imported, they have to be converted to pkcs1 keys. 
Why did rzcoder just ignore this fact?
