### ISSUE TITLE
Discerning between public and private keys?

### ISSUE THREAD

**Issue by georgeedwards** [rzcoder/node-rsa#64]
In the following situation, I have a device and server both of which run node and I want to use `node-rsa` to secure the communication between the two. 

Following the example, I would do something like this:

```
var key = new NodeRSA({b: 512});
 
var text = 'Hello RSA!';
var encrypted = key.encrypt(text, 'base64');
```
and then transmit `encrypted`, however, I can't then decrypt the message, so I should:

1.  (on the server end) generate a key, send only the public key (possibly like `var publicDer = key.exportKey('public');` ), 

2. on the client create a new key, by importing the received public key (?) 

3. send the data encrypted with this to the server 

4. decrypt with the original key (?)

Is this correct, and if so, could this (I believe fairly common) procedure be added to the docs? I don't think the info about creating the public/private keys and transferring a public key is shown.

**Comment by rzcoder** [comment]
Encrypt by public key, decrypt by private. For duplex messaging you should generate keypairs on both client & server, and send public keys each other.
Redme is about API for this lib, not about how to use RSA algoritms.

**Comment by georgeedwards** [comment]
@rzcoder Yes, I get that, but specifically with the api, how do you split the `var key` into a public and private key and then at the client, how would you create/import the received public key to encrypt the data?

**Comment by Eusebius1920** [comment]
If you'd know how to use RSA, you would know that the public key is always a subset of the private key, i.e. the private key always automatically contains the public key.

In the API you can see how to load a key (no matter if it is public or private), how you can determine if a given key-instance is only a public key or a (public and private) keypair. It shows how to encrypt and decrypt a message.

I think it is perfectly sufficent.
