### ISSUE TITLE
Use node-rsa in react-native

### ISSUE THREAD

**Issue by edolfuchs** [rzcoder/node-rsa#65]
I have an application developed in react-native platform. I wonder if node-js is compatible with this platform.

**Comment by rzcoder** [comment]
Me too

**Comment by edolfuchs** [comment]
It appears this error when calling: require ( 'node-rsa')

![captura de tela 2016-08-01 as 12 01 25](https://cloud.githubusercontent.com/assets/12100777/17298324/df1d52f0-57df-11e6-90bc-e97a197ca46e.png)

**Comment by rzcoder** [comment]
So, may be related https://github.com/facebook/react-native/issues/4968

**Comment by SamSaffron** [comment]
confirmed, just hit same issue.

**Comment by rzcoder** [comment]
So, looks like react-native issue ¯\_(ツ)_/¯

**Comment by SamSaffron** [comment]
Possibly, this is something to do with the directory structure in node rsa, I just opened a ticket on the react native side ... I do not think this is #4968

**Comment by SamSaffron** [comment]
the line that is failing is 

https://github.com/rzcoder/node-rsa/blob/master/src/NodeRSA.js#L11

For some reason it is unable to find "crypto" I also can not find it under node_modules here ... where does it come from?

**Comment by rzcoder** [comment]
crypto is core node.js module.

**Comment by SamSaffron** [comment]
aha ... well then this makes 100% sense now ... react native does not ship with crypto so it would need to be pulled in as a dependency

**Comment by SamSaffron** [comment]
@rzcoder it got closed over there ... basically no built in node modules in react native... we should actually reopen this as a "feature request" to add a way of getting it to work in "pure js" without depending on built in node modules. 

this is a spectacular library would be nice if it worked there.

**Comment by d-schloss-mvg** [comment]
How do you generate randomness that is cryptographically secure? The node.js crypto module can guarantee this. I dont know a way of generating it by using "pure js" though... So padding and key-generation is not really cryptographically secure done in pure js, right? (And no Math.random is NOT cryptographically secure...)
There are javascript implementations of secure PRGs (https://github.com/clipperz/javascript-crypto-library), but you still had to feed it with entropy, right?

Modern browsers have at least the Webcrypto-API (https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues) but this is then no longer "pure js".

**Comment by rzcoder** [comment]
@SamSaffron use browserify/webpack to build lib as "pure js" ver.

**Comment by rzcoder** [comment]
@d-schloss-mvg yes, "modern" browsers only.

**Comment by SamSaffron** [comment]
@d-schloss-mvg that is some super important points you are making, absolutely agree with you here. 

I think if react native could ship even with a tiny subset of web crypto (the minimal building block which is the ability to generate randomness) it would do a lot of good for the react native eco system cause people would stop shipping broken key generation

all the required underlying apis exist on iPhone/Android etc... its just a question of exposing them. 

perhaps adding a web-crypto "switch" to node-rsa would be handy?
