### ISSUE TITLE
"InvalidAsn1Error" in firefox 48

### ISSUE THREAD

**Issue by zombiecong** [rzcoder/node-rsa#67]
it works well in firefox 47, but when i tried the latest firefox (version 48) , the browser showed "InvalidAsn1Error". I think the error from "asn1".

**Comment by lszhu** [comment]
also encounter error in ms edge:
InvalidAsn1Error: Expected 0x6: got 0x30

**Comment by zombiecong** [comment]
would you fix it  or not ? @rzcoder

**Comment by rzcoder** [comment]
@zombiecong works nicely for me in ff 48 also in edge. So, look for errors in your code or bundle manager.

**Comment by rzcoder** [comment]
Anyway, Invalid Asn1 Error goes from https://github.com/mcavage/node-asn1 package, you can ask its maintainer for halp.

**Comment by peterabbott** [comment]
@Rzcoder @zombiecong what versions of Node are you using? I am seeing this issue too. We are on Node v6. I think the issue lies with the Buffer class and how the data is being passed into NodeRSA. Node have deprecated `new Buffer(..)` constructor in favour of Buffer.from(...) because it had issues with detecting the type of the underlying data. The error message `0x6: got 0x30` is effectively saying "I was expecting an OID but received a normal string.

**Comment by rzcoder** [comment]
@peterabbott https://travis-ci.org/rzcoder/node-rsa

**Comment by rzcoder** [comment]
@peterabbott @zombiecong I replaced all `new Buffer` calls to `Buffer.from`/`Buffer.alloc` try it from [dev brunch](https://github.com/rzcoder/node-rsa/tree/dev). Only Node 5.10.0+

**Comment by peterabbott** [comment]
Thanks, I'll give it a go. My gut says that it is not a direct issue with node-rsa or even asn1, but with a change in Firefox 48 and Node 6's Buffer class. Potentially the way the key data is being parsed by Buffer and passed into NodeRSA constructor .

All our unit tests pass, but only when we push the code out and only in Firefox 48 on Mac do we see the exception. Also is not consistent

**Comment by peterabbott** [comment]
While still using the existing release version, I updated our client code to use `const key = Buffer.from(rawKey, 'base64', Buffer.byteLength(rawKey, 'base64));` and then pass that into `new NodeRSA(key, 'pkcs8-public-der')` and we no longer see that error message above.

**Comment by zombiecong** [comment]
@rzcoder @peterabbott Thanks. 
My node version is **latest(6.5.0)**. I tried the dev branch in Firefox  48, but it no works, and the error is `"TypeError: "hex" is not a function
"`.
@peterabbott I also tried what you said , and it also not works for me,the error is `TypeError: "base64" is not a function`.

.FYI,I use [closurecompiler](https://github.com/google/closure-compiler) to combine other packages.I am not sure if it would effect the result.

**Comment by peterabbott** [comment]
Sounds like the compiler is missing out a module for the base64 function

**Comment by zombiecong** [comment]
@peterabbott I find the problem is caused by "browserify" , How can you use this library in browser?

**Comment by peterabbott** [comment]
Could you be missing the module base64-js? 

Looking at the source code that is what appears to provide this function. We use webpack/babel to build or stack.
