### ISSUE TITLE
Error Cannot find module 'constants' and 'crypto'

### ISSUE THREAD

**Issue by suclogger** [rzcoder/node-rsa#69]
I tried to use it on a node project like this :
```
        var NodeRSA = require('node-rsa');

        var rsaKeyData = '-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----';

        var rsaKey = new NodeRSA(rsaKeyData);

        console.log(rsaKey.isPublic());
```

But some error occured : 
```
Error Cannot find module 'constants'

Error Cannot find module 'crypto'

ReferenceError: Can't find variable: Buffer
```

So I tried to manually install constants and crypto module , but it still didn't work.

Using webpack and babel : 

```
"dependencies": {
    "babel-runtime": "^6.11.6",
    "crypto-js": "^3.1.6",
    "node-rsa": "^0.4.1",
    "webpack": "^1.13.2"
  },
  "devDependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-preset-stage-1": "^6.13.0",
    "babel-preset-stage-2": "^6.13.0",
    "babel-preset-stage-3": "^6.11.0",
    "json-loader": "^0.5.4"
  }

```

Is there any solution to this problem?

Thanks.

**Comment by rzcoder** [comment]
crypto & constant is native node.js modules 
I guess problem in your webpack config or so

**Comment by suclogger** [comment]
I think you are absolutly correct.
Digging into ...

**Comment by suclogger** [comment]
I solved the problem, but then I got this : 
```
Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11
```

PS. 
    I'm writing a plugin for [PAW](https://luckymarmot.com/paw/).
    The author of paw told me paw is using : 
> the sandboxed javascript engine that is natively provided in macOS X, and that could be considered as a dumbed down version of the one running in Safari.

**Comment by rzcoder** [comment]
No secure random == no crypto algs ¯\_(ツ)_/¯

**Comment by suclogger** [comment]
I tried use `crypto-browserify` directly, and got the same error. 
Some thing is wrong with the environment.
Close.
Thanks a lot.

**Comment by h025** [comment]
I have encountered the same problem, how to solve it!

**Comment by Jithendra71** [comment]
I am also encountering the same issue, Can u explain how to resolve it!

**Comment by alexanderbkl** [comment]
Same, can you explain how you got over it?
