### ISSUE TITLE
Deterministic Key-Pair Generation (Feature Request)

### ISSUE THREAD

**Issue by convexset** [rzcoder/node-rsa#71]
Supposing one had a seed (in the form of a Buffer, say) of some required length, can that be used to generate a deterministic key pair in `node-rsa`?

If so, what are the requirements on that seed and how can it be used?

-----

I've been looking through the code just a little (I guess these are more for me than you), to "stack trace" the relevant aspects:

- `NodeRSA.prototype.generateKeyPair = function (bits, exp) {` on - [L158 of `/src/NodeRSA.js`](https://github.com/rzcoder/node-rsa/blob/master/src/NodeRSA.js#L158)
- `this.keyPair.generate(bits, exp.toString(16));` on [L166 of `/src/NodeRSA.js`](https://github.com/rzcoder/node-rsa/blob/master/src/NodeRSA.js#L166)
- `RSAKey.prototype.generate = function (B, E) {` on [L93 of `/src/libs/rsa.js`](https://github.com/rzcoder/node-rsa/blob/master/src/libs/rsa.js#L93)
- `var ee = new BigInteger(E, 16);` on [L96 of `/src/libs/rsa.js`](https://github.com/rzcoder/node-rsa/blob/master/src/libs/rsa.js#L96) and a few more instantiations [here](https://github.com/rzcoder/node-rsa/blob/master/src/libs/rsa.js#L99) and [here](https://github.com/rzcoder/node-rsa/blob/master/src/libs/rsa.js#L104)
- ... and `var BigInteger = require('./jsbn.js');` points [here](https://github.com/rzcoder/node-rsa/blob/master/src/libs/jsbn.js) where one finds...
```javascript
function BigInteger(a, b) {
    if (a != null) {
        if ("number" == typeof a) {
            this.fromNumber(a, b);
        } else if (Buffer.isBuffer(a)) {
            this.fromBuffer(a);
        } else if (b == null && "string" != typeof a) {
            this.fromByteArray(a);
        } else {
            this.fromString(a, b);
        }
    }
}
```
- ... and `function bnpFromNumber(a, b)` [here](https://github.com/rzcoder/node-rsa/blob/master/src/libs/jsbn.js#L770) where `randomBytes` of the `crypto` package is being used.

**Comment by rzcoder** [comment]
So, what the point of deterministic key-pair?

**Comment by convexset** [comment]
Digital signatures are tough to implement in a non-tech savvy environment. That is having an individual sign off on an action taken (signing a digest of his action) and not being able to repudiate the action (given he is responsible for his "signing password"). One cannot expect a 50 year old chemical engineer to reliably store a 1024-bit private key, but remembering an additional password is not something that would be too problematic.

So one way of doing things would be to generate a key pair determined by the "signing password" "signing" (encrypt with the private key) and then throwing the private key away.

There are simple ways of adding entropy to the password. For example, salting with the user-id (in my case 17 alphanumeric characters) and the creation epoch, both of which are stored in the open. (And a hash of the public key is stored just to support easy client-side checks that the key is correct.)

There are other ways of implementing password-based for example [this](http://link.springer.com/chapter/10.1007%2F978-3-642-29804-2_2) complete with proof of various properties.

But I do not see the value of figuring out the detailed properties of a relatively untested method.

**Comment by convexset** [comment]
Just as a point of note, because of the legal implications of digital signatures in my use case, there will probably be a physical counterpart when a "digital identity" is created. An individual would also have to physically sign some form that includes a digest of the public key (which gets stored), to authorized such a signature to be the legally binding equivalent of that individual's handwritten signature.

**Comment by rzcoder** [comment]
Hm, I still didn't see sense. If you want encryption - just use AES, if you want sign/verify - make key-pair and store it in any (cloud or not) password manager.

**Comment by rzcoder** [comment]
Determined RSA is 100% not secure solution so ¯\_(ツ)_/¯

**Comment by convexset** [comment]
The naive implementation is definitely not secure... if the salt is in the open it can be easily brute forced (so the salt has to be hidden and long).

The point is to enable individuals to take the crucial signing information with them, even if they are naked and swimming. Someone with total access to the server should not be able to sign for them without trying to crack the password.

The point is not encryption, it's signing (associating identify with actions).

Most 40-50 year olds should be able to readily use it without too much difficulty. Remembering a long password is not difficult. Any scheme that involves keeping a key will not work.

**Comment by convexset** [comment]
Closed as unnecessary.

**Comment by nsjames** [comment]
It's a shame this was closed, as this is needed in some cases where the security of the key doesn't matter as much but being able to deterministically generate keys for the same users based on markers unique to that user would be incredibly useful.

For instance:
I am using `node-rsa` to create a **proven** connection between two local sockets. As of right now the key has to be generated on one of the sockets and saved to the user's local storage instead of being deterministically created from various attributes of the user's computer or the origin of the key creator. Which means that if the user clears their cache they will lose the key forever and along with it the permissioned pairing between the two sockets.

**Comment by amir-arad** [comment]
I'm looking for that feature as well
