### ISSUE TITLE
Async RSA key pair generation

### ISSUE THREAD

**Issue by adnan-kamili** [rzcoder/node-rsa#74]
The current RSA key pair generation function is pretty useless for any web app to be used in production:

`var key = new NodeRSA({b: 2048});`

The above line of code took more than 10 seconds to generate the key on my MacBook Air, blocking event loop for more than 10 seconds.

An async version is must for this function to be useful. I wanted to use this lib but ended up writing a node C++ addon for key generation which only takes 0.2 s for generating 2048 bit key pair

**Comment by Eusebius1920** [comment]
Compare with #50 there are methods that could be applied to Webworkers or similar?

**Comment by adnan-kamili** [comment]
In express based web app I can't use web workers server side, forking has a lot of  scalability cost especially when the keys are generated by a web api, unless you use C++ addon API forking seems to be the only option.

**Comment by rzcoder** [comment]
@adnan-kamili I guess on server side you can use an openssl lib like [ursa](https://github.com/quartzjer/ursa) for generate keys.
