### ISSUE TITLE
InvalidAsn1Error only in Safari

### ISSUE THREAD

**Issue by GianniCarlo** [rzcoder/node-rsa#76]
Hi, recently I started having `InvalidAsn1Error: Expected 0x6: got 0x30` when creating a node RSA with a existing public key in Safari:

```
let key = new NodeRSA(myPublicKey, 'public', {encryptionScheme: 'pkcs1'});
```
I transpile everything with webpack.

It worked before with no problems in Safari. Everything still works fine with Chrome 

Safari version: 10.0.1

Any idea how to solve it?

**Comment by rzcoder** [comment]
Try this https://github.com/rzcoder/node-rsa/issues/67#issuecomment-244824452

**Comment by GianniCarlo** [comment]
Updated everything and it got solved 👍
