### ISSUE TITLE
 InvalidAsn1Error: encoding too long

### ISSUE THREAD

**Issue by codey-singh** [rzcoder/node-rsa#77]
I am getting an error like :

>  InvalidAsn1Error: encoding too long

when I am trying to do something like this:
```
var key = new NodeRSA();
var keyData = "-----BEGIN PUBLIC KEY----- <My RSA 2048 public key from PEM file> -----END PUBLIC KEY-----";
key.importKey(keyData, 'pkcs8');
```
even when i tried:

```
var dat = "some string";

fs.readFile("PING_ENCRYPTKEY.pem", function(err, keyData) {
  var key = new NodeRSA();
  console.log(keyData);
  key.importKey(keyData, 'pkcs8');
  var encrypted = key.encrypt(checksum,'hex');
  console.log(encrypted);
  callmethod(encrypted,dat);
});

```
no luck.

Can you please help ?

**Comment by rzcoder** [comment]
Try `pkcs8-public`.

**Comment by codey-singh** [comment]
Thanks @rzcoder. Much appreciated 👍

**Comment by shivam1747** [comment]
keyData = '-----BEGIN RSA PRIVATE KEY-----\n' + my private key + '\n-----END RSA PRIVATE KEY-----';
key = new NodeRSA({b:2048});

encrypt(text){
   key.importKey(keyData, 'pkcs1');
   encrypted = this.key.encrypt(plainText, 'base64');
}

Pops out an error : ERROR InvalidAsn1Error: encoding too long
