### ISSUE TITLE
Signature with extra suffix evaluates as true on verify

### ISSUE THREAD

**Issue by KromDaniel** [rzcoder/node-rsa#80]
Hey,
I think there's a small issue with verify when there's an extra suffix at the signature.

Let's have a look at the next code:

`key.verify(dataToVerify, signature, "utf-8", "base64") //true`

But also

`key.verify(dataToVerify, signature + "aaaa" , "utf-8", "base64") //true`

On prefix it's ok:

`key.verify(dataToVerify, "aaaa" + signature , "utf-8", "base64") //false`

Can you please assist? thanks!

**Using node 6.4.0**

**Comment by rzcoder** [comment]
It's not actually an issue, just nodejs Buffer feature. All text after final padding `=` is ignored when converted to nodejs Buffer.

```js
let a = new Buffer("some test data");
console.log(a)
console.log(a.toString("base64"));
let b = new Buffer("c29tZSB0ZXN0IGRhdGE=an_padding", "base64");
console.log(b);
let c = new Buffer("an_sufix_c29tZSB0ZXN0IGRhdGE=", "base64");
console.log(c);
```

```
<Buffer 73 6f 6d 65 20 74 65 73 74 20 64 61 74 61>
c29tZSB0ZXN0IGRhdGE=
<Buffer 73 6f 6d 65 20 74 65 73 74 20 64 61 74 61>  //same
<Buffer 6a 7f ec b9 f8 b1 fd cd bd b5 94 81 d1 95 cd d0 81 91 85 d1 84>
```
