### ISSUE TITLE
Decrypt fail between NodeJS => JAVA => NodeJS

### ISSUE THREAD

**Issue by totomakers** [rzcoder/node-rsa#90]
I create a new RSA key like following : 

`this.key = new NodeRSA({b: 1024})`
I send the key to the client in `pkcs8-public-der` format with `this.key.exportKey(`pkcs8-public-der`)`

Client receive the data and encrypt some information with the public key

```
Cipher cipher = new Cipher.getInstance("RSA")
KeyFactory factory = KeyFactory.getInstance("RSA")
EncodedKeySpec keyspec= new X509EncodedKeySpec(PKCS8EncodedDer)
PublicKey key = factory.generatePublic(keyspec)
cipher.init(1, key)
cipher.doFinal(data) //bytes[]
```

I receive the data and try to decrypt them with `this.key.decrypt(encodedData)`
But it's fail `Error: Error during decryption (probably incorrect key). Original error: Error: error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error`

**Comment by rzcoder** [comment]
Check client encryption scheme

**Comment by mithun-daa** [comment]
@rzcoder I am running into a similar issue. Can you please elaborate on 
> Check client encryption scheme
