### ISSUE TITLE
Question : Is the encryption / decryption V1.5 compliant?

### ISSUE THREAD

**Issue by ianbale** [rzcoder/node-rsa#96]
I'm using node-rsa to encrypt / decrypt some data. Our app the one the other end cannot decode each  other's data. I can decode our own data just fine using the published key. So, I am assuming there must be some difference between the two encryption settings.

Their spec says
```
The payload data (Appendix A) is encrypted using the TIS private key, using 1024Bit RSA PKCS#1v1.5.
```

This is my encryption code:

```
		let privatekey = await Files.read(appRootDir + '/keys/eticket-private.key')
		let rsakey = new NodeRSA(privatekey,'pkcs1',{encryptionScheme:'pkcs1'})
		let binaryDataAsBuffer = bitsStringToBytes(data)
		let encryptedData = rsakey.encryptPrivate(binaryDataAsBuffer,'hex')
		return encryptedData
```

Is this encrypting using PCSK1 v 1.5?

**Comment by rzcoder** [comment]
why you use `encryptPrivate` ?

**Comment by ianbale** [comment]
No choice... That's the way the system I have to work with is implemented. They chose to use encryption with Private Key / Decrypt with public key as a way to confirm authenticity of the data rather than simply signing it. But, these decisions were taken a long time ago by other people. No possibility of changing that now. I just have to work with it...

In a nutshell, I have to encrypt some travel ticket data (which gets displayed as a barcode). Anyone with a scanner (and a copy of the public key) needs to be able to decode it and verify it. Not sure why they chose to encrypt it. Pointless if you ask me as the real issue is verifying authenticity of the ticket data.

**Comment by rzcoder** [comment]
anyway.. encryptPrivate (decryptPublic) always uses pkcs1 with *not random padding*
